// <auto-generated />
using Backend_Proyecto.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Backend_Proyecto.Migrations;

[DbContext(typeof(AppDbContext))]
[Migration("20260618002500_LecturasMedidorMejoras")]
partial class LecturasMedidorMejoras
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
        // El modelo objetivo completo esta en AppDbContextModelSnapshot.
    }
}
