// <auto-generated />
using System;
using Backend_Proyecto.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Backend_Proyecto.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Backend_Proyecto.Models.Entities.ActividadFontanero", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("AbonadoNumero")
                        .HasColumnType("text");

                    b.Property<string>("AccionRecomendada")
                        .HasColumnType("text");

                    b.Property<string>("AforoNumero")
                        .HasColumnType("text");

                    b.Property<string>("CloroResidual")
                        .HasColumnType("text");

                    b.Property<decimal?>("ConsumoRegistradoM3")
                        .HasColumnType("numeric");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DetalleTrabajoRealizado")
                        .HasColumnType("text");

                    b.Property<string>("DetectoFuga")
                        .HasColumnType("text");

                    b.Property<string>("DiametroTuberia")
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EstadoMedidor")
                        .HasColumnType("text");

                    b.Property<string>("EstadoValidacion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaActividad")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FontaneroId")
                        .HasColumnType("integer");

                    b.Property<string>("FotoEvidenciaBase64")
                        .HasColumnType("text");

                    b.Property<string>("FotoEvidenciaNombre")
                        .HasColumnType("text");

                    b.Property<string>("FotoMedidorBase64")
                        .HasColumnType("text");

                    b.Property<string>("FotoMedidorNombre")
                        .HasColumnType("text");

                    b.Property<string>("HoraControl")
                        .HasColumnType("text");

                    b.Property<string>("HoraFin")
                        .HasColumnType("text");

                    b.Property<string>("HoraInicio")
                        .HasColumnType("text");

                    b.Property<string>("HoraPrueba")
                        .HasColumnType("text");

                    b.Property<decimal?>("LecturaActualM3")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("LecturaAnteriorM3")
                        .HasColumnType("numeric");

                    b.Property<int?>("LecturaMedidorId")
                        .HasColumnType("integer");

                    b.Property<string>("LugarCasa")
                        .HasColumnType("text");

                    b.Property<string>("LugarPrueba")
                        .HasColumnType("text");

                    b.Property<string>("LugarVisita")
                        .HasColumnType("text");

                    b.Property<string>("MaterialesUtilizados")
                        .HasColumnType("text");

                    b.Property<string>("MotivoVisita")
                        .HasColumnType("text");

                    b.Property<string>("NombreAbonado")
                        .HasColumnType("text");

                    b.Property<string>("NumeroAveriaVinculada")
                        .HasColumnType("text");

                    b.Property<string>("ObservacionValidacion")
                        .HasColumnType("text");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text");

                    b.Property<string>("ObservacionesControlOperativo")
                        .HasColumnType("text");

                    b.Property<string>("ObservacionesPresion")
                        .HasColumnType("text");

                    b.Property<string>("Olor")
                        .HasColumnType("text");

                    b.Property<decimal?>("Ph")
                        .HasColumnType("numeric");

                    b.Property<string>("PrioridadSeguimiento")
                        .HasColumnType("text");

                    b.Property<string>("PruebaNumero")
                        .HasColumnType("text");

                    b.Property<string>("RequiereSeguimiento")
                        .HasColumnType("text");

                    b.Property<string>("ResultadoInspeccion")
                        .HasColumnType("text");

                    b.Property<decimal?>("ResultadoPsi")
                        .HasColumnType("numeric");

                    b.Property<string>("ResultadoTrabajo")
                        .HasColumnType("text");

                    b.Property<string>("Sabor")
                        .HasColumnType("text");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Turbiedad")
                        .HasColumnType("text");

                    b.Property<string>("Ubicacion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FontaneroId");

                    b.HasIndex("LecturaMedidorId");

                    b.ToTable("ActividadesFontanero");
                });

            modelBuilder.Entity("Backend_Proyecto.Models.Entities.Averia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Correo")
                        .HasColumnType("text");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DescripcionTrabajo")
                        .HasColumnType("text");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EvidenciaTrabajoBase64")
                        .HasColumnType("text");

                    b.Property<string>("EvidenciaTrabajoNombre")
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaUltimaActualizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("FontaneroAsignadoId")
                        .HasColumnType("integer");

                    b.Property<string>("FotoBase64")
                        .HasColumnType("text");

                    b.Property<string>("FotoNombre")
                        .HasColumnType("text");

                    b.Property<string>("MaterialesUtilizados")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NotasAtencion")
                        .HasColumnType("text");

                    b.Property<string>("NumeroSeguimiento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ObservacionesAdmin")
                        .HasColumnType("text");

                    b.Property<string>("Prioridad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FontaneroAsignadoId");

                    b.HasIndex("NumeroSeguimiento")
                        .IsUnique();

                    b.ToTable("Averias");
                });

            modelBuilder.Entity("Backend_Proyecto.Models.Entities.AveriaHistorial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("AveriaId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Usuario")
                        .HasColumnType("text");

                    b.Property<string>("ValorAnterior")
                        .HasColumnType("text");

                    b.Property<string>("ValorNuevo")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AveriaId");

                    b.ToTable("AveriasHistorial");
                });

            modelBuilder.Entity("Backend_Proyecto.Models.Entities.Comunicado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Fecha")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Comunicados");
                });

            modelBuilder.Entity("Backend_Proyecto.Models.Entities.HistorialLectura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EstadoAnterior")
                        .HasColumnType("text");

                    b.Property<string>("EstadoNuevo")
                        .HasColumnType("text");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LecturaMedidorId")
                        .HasColumnType("integer");

                    b.Property<string>("Observacion")
                        .HasColumnType("text");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("integer");

                    b.Property<string>("UsuarioNombre")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LecturaMedidorId");

                    b.ToTable("HistorialLecturas");
                });

            modelBuilder.Entity("Backend_Proyecto.Models.Entities.LecturaMedidor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CedulaAbonado")
                        .HasColumnType("text");

                    b.Property<decimal>("Consumo")
                        .HasColumnType("numeric");

                    b.Property<bool>("ConsumoAlto")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("ConsumoMesAnterior")
                        .HasColumnType("numeric");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EstadoMedidor")
                        .HasColumnType("text");

                    b.Property<string>("EvidenciaBase64")
                        .HasColumnType("text");

                    b.Property<string>("EvidenciaNombre")
                        .HasColumnType("text");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaLectura")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FontaneroId")
                        .HasColumnType("integer");

                    b.Property<string>("HoraLectura")
                        .HasColumnType("text");

                    b.Property<decimal>("LecturaActual")
                        .HasColumnType("numeric");

                    b.Property<decimal>("LecturaAnterior")
                        .HasColumnType("numeric");

                    b.Property<string>("MotivoVisita")
                        .HasColumnType("text");

                    b.Property<string>("NombreAbonado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NumeroAbonado")
                        .HasColumnType("text");

                    b.Property<string>("NumeroMedidor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ObservacionAdmin")
                        .HasColumnType("text");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text");

                    b.Property<string>("ResultadoInspeccion")
                        .HasColumnType("text");

                    b.Property<int?>("RevisadaPorAdminId")
                        .HasColumnType("integer");

                    b.Property<string>("Ubicacion")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FontaneroId");

                    b.HasIndex("RevisadaPorAdminId");

                    b.ToTable("LecturasMedidor");
                });

            modelBuilder.Entity("Backend_Proyecto.Models.Entities.Proyecto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Proyectos");
                });

            modelBuilder.Entity("Backend_Proyecto.Models.Entities.SecuenciaContador", b =>
                {
                    b.Property<string>("Prefijo")
                        .HasColumnType("text");

                    b.Property<int>("UltimoValor")
                        .HasColumnType("integer");

                    b.HasKey("Prefijo");

                    b.ToTable("SecuenciasContador");
                });

            modelBuilder.Entity("Backend_Proyecto.Models.Entities.Solicitud", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NumeroSeguimiento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("NumeroSeguimiento")
                        .IsUnique();

                    b.ToTable("Solicitudes");
                });

            modelBuilder.Entity("Backend_Proyecto.Models.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ContrasenaHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("NombreUsuario")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Backend_Proyecto.Models.Entities.ActividadFontanero", b =>
                {
                    b.HasOne("Backend_Proyecto.Models.Entities.Usuario", "Fontanero")
                        .WithMany()
                        .HasForeignKey("FontaneroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Backend_Proyecto.Models.Entities.LecturaMedidor", "LecturaMedidor")
                        .WithMany()
                        .HasForeignKey("LecturaMedidorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Fontanero");

                    b.Navigation("LecturaMedidor");
                });

            modelBuilder.Entity("Backend_Proyecto.Models.Entities.Averia", b =>
                {
                    b.HasOne("Backend_Proyecto.Models.Entities.Usuario", "FontaneroAsignado")
                        .WithMany()
                        .HasForeignKey("FontaneroAsignadoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("FontaneroAsignado");
                });

            modelBuilder.Entity("Backend_Proyecto.Models.Entities.AveriaHistorial", b =>
                {
                    b.HasOne("Backend_Proyecto.Models.Entities.Averia", "Averia")
                        .WithMany()
                        .HasForeignKey("AveriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Averia");
                });

            modelBuilder.Entity("Backend_Proyecto.Models.Entities.HistorialLectura", b =>
                {
                    b.HasOne("Backend_Proyecto.Models.Entities.LecturaMedidor", "LecturaMedidor")
                        .WithMany()
                        .HasForeignKey("LecturaMedidorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LecturaMedidor");
                });

            modelBuilder.Entity("Backend_Proyecto.Models.Entities.LecturaMedidor", b =>
                {
                    b.HasOne("Backend_Proyecto.Models.Entities.Usuario", "Fontanero")
                        .WithMany()
                        .HasForeignKey("FontaneroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Backend_Proyecto.Models.Entities.Usuario", "RevisadaPorAdmin")
                        .WithMany()
                        .HasForeignKey("RevisadaPorAdminId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Fontanero");

                    b.Navigation("RevisadaPorAdmin");
                });
#pragma warning restore 612, 618
        }
    }
}
